# Generated by Django 4.0.4 on 2022-05-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt_familiares', '0002_alter_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='familiar',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
